---
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - id: scanner-trivy
    main: ./cmd/scanner-trivy/main.go
    binary: alauda-scanner-trivy
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .FullCommit }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs'
      - '^test'
      - '^release'

release:
  footer: >-

    ---

    This release is intended for use only as part of the Alauda product suite. 
    It is not recommended for use by individuals or teams outside of Alauda. 
    Any consequences arising from its use are the sole responsibility of the user.
