---
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - id: scanner-trivy
    main: ./cmd/scanner-trivy/main.go
    binary: scanner-trivy
    env:
      - CGO_ENABLED=0
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs'
      - '^test'
      - '^release'
dockers:
  - image_templates:
      - "docker.io/goharbor/harbor-scanner-trivy:{{ .Tag }}"
    ids:
      - scanner-trivy
    build_flag_templates:
      - "--label=org.label-schema.schema-version=1.0"
      - "--label=org.label-schema.name={{ .ProjectName }}"
      - "--label=org.label-schema.description=Harbor scanner adapter for Trivy"
      - "--label=org.label-schema.vendor=Harbor community"
      - "--label=org.label-schema.version={{ .Version }}"
      - "--label=org.label-schema.build-date={{ .Date }}"
      - "--label=org.label-schema.vcs=https://github.com/goharbor/harbor-scanner-trivy"
      - "--label=org.label-schema.vcs-ref={{ .FullCommit }}"
