---
apiVersion: v1
appVersion: 0.31.1
description: Harbor scanner adapter for Trivy
keywords:
  - scanner
  - harbor
  - vulnerability
name: harbor-scanner-trivy
sources:
  - https://github.com/aquasecurity/harbor-scanner-trivy
version: 0.31.1